### ISSUE TITLE
readme base_model error

### ISSUE THREAD

**Issue by yance-dev** [autodistill/autodistill-grounding-dino#1]
Quickstart for  GroundingDINO but use GroundedSAM:

[base_model = GroundedSAM(ontology=CaptionOntology({"shipping container": "container"}))](https://github.com/autodistill/autodistill-grounding-dino/blob/a465b415ec53e7c7f809619abc5429adb5a12809/README.md?plain=1#L40)

change to GroundingDINO may be better :
```
base_model = GroundingDINO(ontology=CaptionOntology({"shipping container": "container"}))
```

**Comment by capjamesg** [comment]
This has now been fixed. Thank you!
