### ISSUE TITLE
Cannot Install via PIP

### ISSUE THREAD

**Issue by NapasinKuna** [autodistill/autodistill-grounding-dino#6]
I'm currently using Python version 3.10.13.

I cannot install this autodistill-grounding-dino and autodistill-grounded-sam using

`pip install autodistill-grounding-dino`
and
`pip install autodistill-grounded-sam`

**autodistill-grounding-dino**
![image](https://github.com/autodistill/autodistill-grounding-dino/assets/33731737/52623101-2448-425c-8d05-a8ed9d183b8a)
**autodistill-grounded-sam**
![image](https://github.com/autodistill/autodistill-grounding-dino/assets/33731737/e5539870-a3d7-4075-b961-7485d47bf564)

**Comment by capjamesg** [comment]
Hello! Were you able to fix this issue?
